# Generated by Django 5.2.8 on 2025-11-13 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'verbose_name_plural': 'Cloths'},
        ),
        migrations.AddField(
            model_name='cloth',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cloth',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
