# Generated by Django 5.2.8 on 2025-11-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitem',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='bagitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='BagItem',
        ),
    ]
